=== NathSpeeckaert/examen_web_stat/XML/immo.dtd
<!ELEMENT immo (bien+)>
<!ELEMENT bien (appartement*,maison*)>

<!ELEMENT appartement (detail)>

<!ELEMENT maison (detail)>
    <!ATTLIST maison facade (2|3|4) #REQUIRED
              		 etage (plain-pied|1|2|3|4) #REQUIRED>

<!ELEMENT detail (type, localisation, prix, extra)>
    <!ATTLIST detail chambre CDATA #REQUIRED
              		 sdb CDATA #REQUIRED
              		 vitrage (simple|double|triple) #REQUIRED
             		 cc (non|gaz|mazout)  #REQUIRED
              		 surface CDATA #REQUIRED>

<!ELEMENT extra EMPTY>
    <!ATTLIST extra jardin (oui|non) #REQUIRED
              		garage (oui|non) #REQUIRED>
                
<!ELEMENT type EMPTY>
   <!ATTLIST type cession (location|vente) #REQUIRED>



<!ELEMENT prix (#PCDATA)>

<!ELEMENT localisation EMPTY>
    <!ATTLIST localisation commune (Anderlecht|Auderghem|Berchem-Sainte-Agathe|Bruxelles|Etterbeek|Evere|Forest|Ganshoren|Ixelles|Jette|Koekelberg|Molenbeek-Saint-Jean|Saint-Gilles|Saint-Josse-ten-Noode|Schaerbeek|Uccle|Watermael-Boitsfort|Woluwé-Saint-Lambert|Woluwé-Saint-Pierre) #REQUIRED>

=== NathSpeeckaert/examen_web_stat/XML/immo2.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="immo2.xsl"?>

<!DOCTYPE immo SYSTEM "immo.dtd">
<immo>

    <bien>
        <maison facade="2" etage="2"> 
            <detail chambre="6" sdb="1" vitrage="double" cc="gaz" surface="172" >
                <type cession="vente"></type>
                <localisation commune="Evere"></localisation>
                <prix>299000</prix>
                <extra jardin="oui" garage="non"></extra>
            </detail>
        </maison>
    </bien>

    <bien>  

        <maison facade="2" etage="2"> 
            <detail chambre="5" sdb="2" vitrage="double" cc="gaz" surface="185" >
                <type cession="vente"></type>
                <localisation commune="Anderlecht"></localisation>
                <prix>325000</prix>
                <extra jardin="oui" garage="non"></extra>
            </detail>
        </maison>
    </bien>
    <bien>    

        <maison facade="2" etage="2"> 
            <detail chambre="3" sdb="1" vitrage="double" cc="non" surface="60" >
                <type cession="vente"></type>
                <localisation commune="Auderghem"></localisation>
                <prix>205000</prix>
                <extra jardin="oui" garage="non"></extra>
            </detail>
        </maison>
    </bien>
    <bien>
        <maison facade="2" etage="3"> 
            <detail chambre="4" sdb="2" vitrage="simple" cc="non" surface="150" >
                <type cession="vente"></type>
                <localisation commune="Molenbeek-Saint-Jean"></localisation>
                <prix>219000</prix>
                <extra jardin="non" garage="non"></extra>
            </detail>
        </maison>
    </bien>
    <bien>
        <maison facade="2" etage="3"> 
            <detail chambre="4" sdb="4" vitrage="simple" cc="mazout" surface="150" >
                <type cession="vente"></type>
                <localisation commune="Molenbeek-Saint-Jean"></localisation>
                <prix>300000</prix>
                <extra jardin="oui" garage="oui"></extra>
            </detail>
        </maison>
    </bien>
    <bien>
        <maison facade="4" etage="3"> 
            <detail chambre="6" sdb="3" vitrage="triple" cc="gaz" surface="300" >
                <type cession="location"></type>
                <localisation commune="WoluwÃ©-Saint-Lambert"></localisation>
                <prix>4000</prix>
                <extra jardin="oui" garage="oui"></extra>
            </detail>
        </maison>
    </bien>
    <bien>
        <maison facade="2" etage="3"> 
            <detail chambre="4" sdb="2" vitrage="double" cc="gaz" surface="200" >
                <type cession="location"></type>
                <localisation commune="Ixelles"></localisation>
                <prix>2000</prix>
                <extra jardin="oui" garage="oui"></extra>
            </detail>
        </maison>
    </bien>
    <bien>    
        <maison facade="2" etage="2"> 
            <detail chambre="5" sdb="3" vitrage="double" cc="gaz" surface="300" >
                <type cession="location"></type>
                <localisation commune="Schaerbeek"></localisation>
                <prix>2050</prix>
                <extra jardin="non" garage="non"></extra>
            </detail>
        </maison>
    </bien>
    <bien>
        <maison facade="2" etage="2"> 
            <detail chambre="4" sdb="2" vitrage="double" cc="gaz" surface="200" >
                <type cession="location"></type>
                <localisation commune="Anderlecht"></localisation>
                <prix>2100</prix>
                <extra jardin="non" garage="non"></extra>
            </detail>
        </maison>
    </bien>
    <bien>
        <appartement>
            <detail chambre="2" sdb="1" vitrage="double" cc="mazout" surface="75" >
                <type cession="location"></type>
                <localisation commune="Ixelles"></localisation>
                <prix>900</prix>
                <extra jardin="non" garage="oui"></extra>
            </detail>
        </appartement>       
    </bien>
    <bien>
        <appartement>
            <detail chambre="1" sdb="1" vitrage="double" cc="gaz" surface="60" >
                <type cession="location"></type>
                <localisation commune="Schaerbeek"></localisation>
                <prix>750</prix>
                <extra jardin="non" garage="non"></extra>
            </detail>
        </appartement>
    </bien>
    <bien>
        <appartement>
            <detail chambre="3" sdb="1" vitrage="double" cc="gaz" surface="150" >
                <type cession="location"></type>
                <localisation commune="Anderlecht"></localisation>
                <prix>1250</prix>
                <extra jardin="oui" garage="non"></extra>
            </detail>
        </appartement>                      
    </bien>
</immo>
